sudo: false
language: python

notifications:
  email: false

python:
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true
  include:
  - os: linux
    python: "3.7-dev"
  # XXX need miniconda for Python on OS X
  #- os: osx
    #python: "3.6"
  allow_failures:
  - os: linux
    python: "3.7-dev"
  #- os: osx
    #python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python -m mtprof.tests -v
